### ISSUE TITLE
Create skeleton collector with Prometheus endpoint

### ISSUE THREAD

**Issue by yonch** [perfpod/memory-collector#19]
The project will deliver a binary that collects memory interference metrics, and exposes them to observability backends.

In this issue, we create a skeleton implementation of that binary, that sets up Prometheus collection with a simple `up` metric whose value is 1.

Prometheus's [client_golang library](https://github.com/prometheus/client_golang) provides the endpoint and metric functionality. The [guide](https://prometheus.io/docs/guides/go-application/) walks through a skeleton application

- [ ] Create a `main.go` file in `cmd/collector`
- [ ] Expose an endpoint on a known fixed port
- [ ] Expose the `up` metric with value 1
- [ ] Manually verify: query the endpoint using `curl` or `wget` (the guide above uses `curl`)
- [ ] Move the code into a function (not `main()`) 
~Add an [integration test](https://go.dev/doc/tutorial/add-a-test) that verifies the metrics are up, [using client_golang's testutil](https://albertmoreno.dev/posts/testing-prometheus-metrics-in-integration-tests-in-golang/) (in the second half of the writeup).~ (moved to issue #20)

**Comment by atimeofday** [comment]
I'll see what I can do

**Comment by atimeofday** [comment]
5/6 done and pushed to a fork for review before a complete PR: https://github.com/atimeofday/memory-collector

6/6 looks like a steep learning curve, I'll give it another shot when I have more spare time and/or assistance.

**Comment by yonch** [comment]
Looks good! If the test is larger than originally thought let's split it to its own issue and get this one to done.
