### ISSUE TITLE
Find what distributions support Linux resctrl

### ISSUE THREAD

**Issue by yonch** [perfpod/memory-collector#6]
The Linux `resctrl` subsystem provides access to memory bandwidth and cache measurements and control. It is compiled into the kernel using flags:
- `CONFIG_X86_CPU_RESCTRL` (since v5.0)
- `CONFIG_X86_RESCTRL`
- [`CONFIG_RESCTRL`](https://github.com/torvalds/linux/commit/90802938f7e88045ace123e105e22e8c3e7f9c7e#diff-30397f61d1661eb57fd49221ec6a29cb96afdbd0d8084558aabd464530de0283L12)
- [`CONFIG_INTEL_RDT`](https://github.com/torvalds/linux/commit/a6f771c9bf4eea2da1516e70c283ede61a7d666f#diff-30397f61d1661eb57fd49221ec6a29cb96afdbd0d8084558aabd464530de0283L9)
- [`CONFIG_INTEL_RDT_A`](https://github.com/torvalds/linux/commit/1640ae9471ae41eb18d2b214f1f40af3c4ed3828#diff-721a170a1097365c094c385ffcb09225384ba983423b0a0197ee35e7fe28ea37L9)

I plan to submit a PR to https://github.com/nyrahul/linux-kernel-configs to create a table of distributions that support resctrl out-of-the-box.

**Comment by amosomokpo** [comment]
I'm thinking of creating a script/image that can verify both kernel and CPU support for x86(intel & AMD) and the various monitoring and allocation features they have. Probably an image is better to run across kubernetes clusters to annotate nodes with support later than the line.

**Comment by yonch** [comment]
Merging nyrahul/linux-kernel-configs#27 solves this ticket. 

@amosomokpo I'll start a different ticket for the script idea.
